<?php

/**
 * @file
 * Install, update and uninstall functions for the aaddweb module.
 */

/**
 * Implements hook_install().
 */
function addweb_install() {
  \Drupal::configFactory()->getEditable('addweb.settings')
    ->set('assetsType', 'default')
    ->set('assetsPaths', 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css,https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js')
    ->save();
}
