<?php

/**
 * @file
 * Functions for the addweb module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;

/**
 * Implementation of addweb_help().
 */
function addweb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.addweb':
      $output = '<p>' . t('This module places custom CSS and JS CDN') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function addweb_preprocess_page(&$variables) {
  $config = \Drupal::config('addweb.settings');
    // assets get setting values.
    $variables['#attached']['drupalSettings']['assetsType'] = $config->get('assetsType');
    $variables['#attached']['drupalSettings']['assetsPaths'] = $config->get('assetsPaths');
    if ($variables['#attached']['drupalSettings']['assetsType'] == 'default') {
      $variables['#attached']['library'][] = 'addweb/addweb';
    }
}

/**
 * Implements hook_page_attachments().
 */
function addweb_page_attachments(&$attachments) {
  $config = \Drupal::config('addweb.settings');
  $assetsType = $config->get('assetsType');
  $assetsPaths = $config->get('assetsPaths');
  $assetsPathsJs = explode(',', $assetsPaths);

  if ($assetsType == 'custom') {
    foreach ($assetsPathsJs as $key => $value) {
        if(strpos($value, '.js') !== false) {
          $assetsArray = [
            '#tag' => 'script',
            '#attributes' => ['type' => 'text/javascript', 'src' => $value],
            '#weight' => 1,
            'addweb_script',
          ];
        } 
        if(strpos($value, '.css') !== false) {
          $assetsArray = [
            '#tag' => 'style',
            '#attributes' => ['rel' => 'stylesheet', 'herf' => $value],
            '#weight' => 1,
          ];
        }
        $attachments['#attached']['html_head'][] = [$assetsArray, $key];
    }
  }
}
